version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.github.Angeschossen:LandsAPI
    versions:
    - 5.0.5
    - 5.1.13
    - 5.2.1
    - 5.2.2
    - 5.2.4
    - 5.2.5
    - 5.3.2
    - 5.3.3
    - 5.4.0
    - 5.4.12
    - 5.5.5
  - dependency-name: org.bstats:bstats-bukkit
    versions:
    - 2.1.0
